name: markusmuoth
favicon: null
layout_spectrum: 0.25041
typography_spectrum: 0.5412290764506906
title: markusmuoth-photo-video-works
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#333333'
    - '#5f5f5f'
    - '#939393'
  brandStrength: 0.5625
  lightness: 0.25272134435363114
  saturation: 0.09051956539042294
  rhythmicContrast: 0.05357334320433438
purpose: []
