name: markusmuoth
favicon: null
layout_spectrum: 0.5361175758298486
typography_spectrum: 0.5412290764506906
title: markusmuoth-photo-video-works
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7527047349140048
  lightness: 0.25272134435363114
  saturation: 0.09051956539042294
  rhythmicContrast: 0.05357334320433438
purpose: []
